### ISSUE TITLE
Unfold when templater command runs

### ISSUE THREAD

**Issue by imeed166** [liamcain/obsidian-creases#12]
I'm using a templater command that replace `- [x]` with `- [ ]`, here is the code 
```
<%*
const text = tp.file.content
const output = text.replaceAll('- [x]','- [ ]')
const file = tp.file.find_tfile(tp.file.title)
await app.vault.modify(file, output)
_%>
```
And when I execute this command, (because the text being replaced is underneath a folded heading with a crease) it automatically unfolds the heading. 

Is the plugin supposed to behave this way ? Is there a way to make it stay folded even when executing the templater command ?

**Comment by liamcain** [comment]
Hi @imeed166, this behavior is expected because your template is using `vault.modify`. The `modify` function is "dumb" in that it replaces all the contents with a file with new contents. So Obsidian doesn't know anything about the nature of the changes. It can't tell that most of the content is the same and that just the checkboxes are unchecked. So the expected behavior is that all your fold information is cleared out. This behavior will happen with or without this plugin.

The simplest fix for now is to include the following at the end of your template:
`app.commands.executeCommandById('creases:fold');`

That will refold your creases after unchecking the checkboxes.

---

A better fix would involve using CodeMirror to actually just modify the lines with the checkboxes. But I think this behavior is likely too complex for a simple template.

**Comment by imeed166** [comment]
Thank you for explaining and for providing me with two alternative solutions.

**Comment by imeed166** [comment]
> The simplest fix for now is to include the following at the end of your template:
> `app.commands.executeCommandById('creases:fold');`

Sorry to bother you, but the added line doesn't re-fold the heading.

**Comment by imeed166** [comment]
plugin in lastest version (0.4.3)
file: [testing.md](https://github.com/liamcain/obsidian-creases/files/8207530/testing.md)
template:
```
<%*
const text = tp.file.content
const output = text.replaceAll('- [x]','- [ ]')
const file = tp.file.find_tfile(tp.file.title)
await app.vault.modify(file, output)
_%>
```

**Comment by liamcain** [comment]
Just to confirm, does the heading have a little 👕 next to it? 

<img width="225" alt="image" src="https://user-images.githubusercontent.com/693981/157271826-6fad803c-671f-4ece-9b71-3df675b9ab35.png">

If it doesn't, then it's just a regular fold.

For the command I sent to work, you'd need to add: `%% fold %%` to the heading so that it looks like this:

<img width="248" alt="image" src="https://user-images.githubusercontent.com/693981/157271977-9a423c70-8bfe-45bb-97c9-9e02f31d8d2d.png">

Let me see if there's a better solution though. I'll get back to you.

**Comment by imeed166** [comment]
> Just to confirm, does the heading have a little 👕 next to it?

Yes, it's there.

> Let me see if there's a better solution though. I'll get back to you.

Okay, thank you.

**Comment by liamcain** [comment]
So it's ugly but you can do this:

```
<%*
const text = tp.file.content
const output = text.replaceAll('- [x]','- [ ]')
const file = tp.file.find_tfile(tp.file.title)
await app.vault.modify(file, output)
setTimeout(() => app.commands.executeCommandById('creases:fold'), 50)
_%>
```

**Comment by imeed166** [comment]
It works, thank you for your time.
