### ISSUE TITLE
Is this plugin still working?

### ISSUE THREAD

**Issue by Kullenej** [liamcain/obsidian-creases#6]
I can't seem to get it to work

**Comment by ashishbhateja** [comment]
not for me either

**Comment by liamcain** [comment]
Yes, this plugin was using some private APIs that have since changed since its initial release so it doesn't work currently. I did a major overhaul though in #7 where I tried to figure out how this plugin fits into Obsidian now that there's Live Preview and folding is persisted between Edit and Reading view.

My current thinking is: Just add a command to "toggle note creases" and just open or close the folds.

I'm curious if people find that useful though or what you were using this plugin for previously.

**Comment by liamcain** [comment]
I released v0.3.0 which is basically a reimagining of the plugin. Closing this issue for now but feel free to file new issues/feature requests about the new version.
